language: scala
services:
- docker

before_install:
- git fetch --tags
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - stage: test
    jdk:
    - openjdk8
    - openjdk11
    scala:
    - 2.12.8
    install:
    - pip install --user codecov
    script: sbt ++$TRAVIS_SCALA_VERSION validate
    after_success:
    - codecov
  - stage: release
    script: docker login -u $DOCKER_USER -p $DOCKER_PASS && sbt docker:publish

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0c488817d5dc313a8cc7
    on_success: change
    on_failure: always
    on_start: never
